config/routes.rb
Rails.application.routes.draw do

resources :taches

end

app/models/tach.rb
class Tach < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/taches_controller.rb
class TachesController < ApplicationController
  before_action :set_tach, only:[:show, :edit, :update, :destroy]
  def index
    @taches = Tach.all
  end

  def show

  end

  def new
    @tach = Tach.new
  end

  def create
    @tach = Tach.new(tach_params)
    @tach.save
    redirect_to taches_path(@tach)
  end

  def edit
  end

  def update
    @tach.update(tach_params)
    redirect_to taches_path(@tach)
  end

  def destroy
    @tach.destroy
    redirect_to taches_path
  end

  def set_tach
    @tach = Tach.find(params[:id])
  end

  def tach_params
    params.require(:tach).permit(:name, :statut)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taches_helper.rb
module TachesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tachesmanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/taches/edit.html.erb
<h1>Taches#edit</h1>
<p></p>
<%= form_for(@tach) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/taches/index.html.erb
<h1>Taches#index</h1>
<p>
<% @taches.each do |tach| %>
 <p><%= link_to tach.name, tach_path(tach) %></p>
  <p><%= link_to "Delete", tach_path(tach),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
<% end %>

app/views/taches/new.html.erb
<h1>Taches#new</h1>

<p><%= form_for(@tach) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %></p>

app/views/taches/show.html.erb
<h2><%= @tach.name %></h2>
<p><%= @tach.statut %></p>